use_frameworks!

platform :ios, '12.2'

target 'ios-sabycom-demo' do
  pod 'Sabycom', :path => '../ios-sabycom-sdk'

  target 'Sabycom_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['SWIFT_VERSION'] = '5.4.2'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.2'
    end
  end
end
