source 'git@git.sbis.ru:mobileworkspace/specs.git'
source 'git@git.sbis.ru:sbis/core-cocoapods-specs.git'

use_modular_headers!

platform :ios, '12.0'

def common_pods_for_target
  pod 'Sabycom', :path => '../ios-sabycom-sdk'
end

target 'ios-sabycom-demo' do
  common_pods_for_target
end

target 'ios-sabycom-demo-local' do
  common_pods_for_target
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.9'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
